# Generated by Django 3.0 on 2020-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201013_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_stock',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
