# Generated by Django 3.0 on 2020-10-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_qty',
            field=models.IntegerField(default=5),
        ),
    ]
