# Generated by Django 3.0 on 2020-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201029_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_qty',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
